"""Assemble data.js for the site: living-dex rows + spin-off fixes + Sinnoh Dex (seen/caught) data."""
import sys, json
sys.path.insert(0, '/home/claude/scripts')
from site_data import OUT, TIERS
out_path = sys.argv[1]
BY = {o['id']: o for o in OUT}

# ---- spin-off sources (verified on Bulbapedia / BulbaNews / Serebii) ----
RANGER = ['Pokémon Ranger (the first DS Ranger game): beat the main story.', 'On the Ranger Net menu choose password entry and enter P8M2-9D6F-43H7 to unlock the "Recover the Precious Egg" mission.',
          'Clear the mission, then use Ranger Net to send the Manaphy Egg to Diamond, Pearl or Platinum (each cart can receive one egg; each egg goes to one cart).',
          'Hatch it, then trade it to your Platinum if it went to D/P.']
BY[490].update(c='Spin-off', src='Pokémon Ranger (DS) → D/P/Platinum', tr='Egg sent from Pokémon Ranger, hatched in Gen 4', rank=6, steps=RANGER,
               w='Pokémon Ranger special mission egg (code P8M2-9D6F-43H7 after beating the game).', need='Pokémon Ranger (DS) cart')
BY[489].update(c='Spin-off', src='Breed Manaphy, or My Pokémon Ranch (Wii)', tr='Breed in Platinum, or trade from Diamond/Pearl', rank=6,
               steps=['Easiest: get Manaphy from Pokémon Ranger (see Manaphy), then Day-Care Manaphy + Ditto — the egg hatches Phione.',
                      'OR My Pokémon Ranch (Wii): once 250 Pokémon are deposited (ranch level 15), Hayley asks for a Leafeon. Bring one from Diamond/Pearl and she trades you a Phione (Lv50).',
                      'The English Ranch only connects to Diamond/Pearl (its Platinum update was Japan-only), so trade it D/P → Platinum afterwards.'],
               w='Breed Manaphy with Ditto, or My Pokémon Ranch trade (250 deposited + Leafeon).', need='Manaphy, or My Pokémon Ranch')
BY[151].update(c='Spin-off', src='My Pokémon Ranch (Wii) → Diamond/Pearl', tr='Ranch → Diamond/Pearl → DS trade to Platinum', rank=6,
               steps=['My Pokémon Ranch (Wii): deposit Pokémon from Diamond/Pearl until 999 are on the ranch (ranch level 25).',
                      'Hayley then asks for any Pokémon Egg. Bring one and she trades you Mew (Lv50).',
                      'The English Ranch only works with Diamond/Pearl, not Platinum, so withdraw Mew to D/P and trade it to Platinum.',
                      'The Wii Shop closed in January 2019 — this only works if Ranch is already downloaded on a Wii.',
                      'Otherwise Mew is event-only (fan-run WFC).'],
               w='My Pokémon Ranch trade at 999 deposited + an Egg. Otherwise event only.', need='My Pokémon Ranch on a Wii + Diamond/Pearl')
BY[385]['steps'] = ['Pokémon Colosseum bonus disc (North American pre-order) or Pokémon Channel (European GameCube) gives a Jirachi you can send to a Gen 3 game, then Pal Park it.',
                    'Otherwise event only (fan-run WFC).']
BY[385]['w'] = 'Colosseum bonus disc (US) / Pokémon Channel (EU) on GameCube, or an event.'

# ---- Sinnoh Dex ----
sinnoh = json.load(open('/home/claude/work/sinnoh.json'))
seen = {int(k): v for k, v in json.load(open('/home/claude/work/seen.json')).items()}
TIPS = {
    480: 'Seen during the story at Lake Acuity (Uxie). It\'s caught after the story in Acuity Cavern.',
    481: 'Seen during the story at Lake Verity. After the story, interact with it in Verity Cavern and it starts roaming.',
    482: 'Seen during the story at Lake Valor (Azelf).',
    483: 'Seen at Spear Pillar during the story climax. Catchable after the National Dex.',
    484: 'Seen at Spear Pillar during the story climax. Catchable after the National Dex.',
    487: 'Seen and catchable in the Distortion World during the story (Lv47).',
    490: 'Read the book on the desk in Mr. Backlot\'s office in the Pokémon Mansion (Route 212). That registers Manaphy as seen — no event needed.',
    479: 'Old Chateau 2F, left room: check the TV at night. Battling it registers it as seen.',
    442: 'Hallowed Tower (Route 209) + Odd Keystone + 32 Underground conversations. Also on Champion Cynthia\'s team.',
    425: 'Valley Windworks gate on Fridays.',
    387: 'Your starter, or seen on Barry\'s / Dawn\'s team — they pick the other two.',
    390: 'Your starter, or seen on Barry\'s / Dawn\'s team — they pick the other two.',
    393: 'Your starter, or seen on Barry\'s / Dawn\'s team — they pick the other two.',
}
SIN = []
for s in sinnoh:
    t = seen.get(s['id'], {})
    SIN.append(dict(rn=s['rn'], id=s['id'], how=s['how'], wild=s['story'], locs=s['locs'], tip=TIPS.get(s['id'], ''),
                    tr=t.get('list', []), more=t.get('more', 0), trN=t.get('story', 0), trAll=t.get('n', 0)))

open(out_path, 'w').write('/* Generated by tools/gen.py — do not edit by hand. */\nwindow.DATA_VERSION="2026-10-07b";\nwindow.TIERS=' + json.dumps(TIERS, ensure_ascii=False) +
                          ';\nwindow.DEX=' + json.dumps(OUT, ensure_ascii=False, separators=(',', ':')) + ';\nwindow.SINNOH=' + json.dumps(SIN, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('ok', len(OUT), len(SIN))
